spring:
  application:
    name: eureka-server

server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#    не хотим получать информацию реестра от Eureka Server
    eureka-server-connect-timeout-seconds: 60
#    время ожидания (1 минута) до истечения тайм-аута соединения с Eureka Server
    eureka-service-url-poll-interval-seconds: 15
#    каждые 15 секунд запрашивать изменения об информации с сервера
    use-dns-for-fetching-service-urls: false
#    запрет dns
    prefer-same-zone-eureka: true
#    использовать сервер eureka в той же зоне
    healthcheck:
      enabled: true
#      для клиента включим healthcheck
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
#      явный маршрут к серверам eureka (serviceUrl)
  server:
    renewalPercentThreshold: 0.49
#    если возникнут проблемы в сети или наш сервер выйдет из строя мы хотим запретить клиент
  instance:
    hostname: my-eureka-server.com
    lease-renewal-interval-in-seconds: 20
#    установить время, по которому сервер будет ожидать эхо запрос от клиента о том что он жив (20 секунд)
    lease-expiration-duration-in-seconds: 70
#    Если Eureka Server не видел обновления в течение 70 секунд, он удаляет экземпляр из своего реестра